# This file was generated by GoReleaser. DO NOT EDIT.
cask "mb-cli" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "ee2cc70b1e2d6fdbb604354d70adbedead23a914cf8f12a5bd04eb6bab44a229"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/mb-cli-darwin-amd64"
      binary "mb-cli-darwin-amd64", target: "mb-cli"
    end
    on_arm do
      sha256 "3afa928fe9027e1699ace5b156c33309ec4c9c78edb9fa4b60f54da52353c7c2"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/mb-cli-darwin-arm64"
      binary "mb-cli-darwin-arm64", target: "mb-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "d859861a444398a04569c3342a347a50749b162f3bb32938a0735d2172c540d9"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/mb-cli-linux-amd64"
      binary "mb-cli-linux-amd64", target: "mb-cli"
    end
    on_arm do
      sha256 "3d1fcf05d6aac205aef5779aa955d5b0fdec9458c4e1b70cf29749aab8473c86"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/mb-cli-linux-arm64"
      binary "mb-cli-linux-arm64", target: "mb-cli"
    end
  end

  name "mb-cli"
  desc "CLI for Memory Bank documentation tooling"
  homepage "https://github.com/dapi/memory-bank-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
