# This file was generated by GoReleaser. DO NOT EDIT.
cask "memory-bank-cli" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "eaf2b29a22ca5ee0a051d8490d5d9a9570e378a127e00197e4b11cf47ebb53c1"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-darwin-amd64"
      binary "memory-bank-cli-darwin-amd64", target: "memory-bank-cli"
    end
    on_arm do
      sha256 "fd3f6199a29b5d71103108b157696c1ca91d02b6228399a7cfe19a6cc03e9158"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-darwin-arm64"
      binary "memory-bank-cli-darwin-arm64", target: "memory-bank-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "40e99425edd9080f2c966de6e9bd6b9230d01c29d352badcfef144810cfeb710"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-linux-amd64"
      binary "memory-bank-cli-linux-amd64", target: "memory-bank-cli"
    end
    on_arm do
      sha256 "a4eb97ec18baa14c7e7c5799c34b0584a6553c32df31798d78f444a4ed81ccf7"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-linux-arm64"
      binary "memory-bank-cli-linux-arm64", target: "memory-bank-cli"
    end
  end

  name "memory-bank-cli"
  desc "CLI for Memory Bank documentation tooling"
  homepage "https://github.com/dapi/memory-bank-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
