# This file was generated by GoReleaser. DO NOT EDIT.
cask "memory-bank-cli" do
  version "1.2.2"

  on_macos do
    on_intel do
      sha256 "31fa6ba19fde7bd31567a02eb0ad9f1e485a494063842a483f4b349e44ef524a"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-darwin-amd64"
      binary "memory-bank-cli-darwin-amd64", target: "memory-bank-cli"
    end
    on_arm do
      sha256 "841db3ca5fa8b657157d1163468b1c4a553a1fe4ff25846d5ce28af96632eb73"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-darwin-arm64"
      binary "memory-bank-cli-darwin-arm64", target: "memory-bank-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d1f38bfc2a8014ce52ae7204c066593951eb7b3c75282214e911d63ac0011dd"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-linux-amd64"
      binary "memory-bank-cli-linux-amd64", target: "memory-bank-cli"
    end
    on_arm do
      sha256 "b45a820c0bb037941a72a887198ef734fe95cae8643a3597baa84eed65862bf7"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-linux-arm64"
      binary "memory-bank-cli-linux-arm64", target: "memory-bank-cli"
    end
  end

  name "memory-bank-cli"
  desc "CLI for Memory Bank documentation tooling"
  homepage "https://github.com/dapi/memory-bank-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
