# This file was generated by GoReleaser. DO NOT EDIT.
cask "memory-bank-cli" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "e2630e9df620334e2a70a6d2e4a3ebb54e1658a976f33375d8dd764431554322"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-darwin-amd64"
      binary "memory-bank-cli-darwin-amd64", target: "memory-bank-cli"
    end
    on_arm do
      sha256 "4d3a34f6a016edd29ee88437f8a35162dc847086156e537b985697b965fd3ec8"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-darwin-arm64"
      binary "memory-bank-cli-darwin-arm64", target: "memory-bank-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "99644ff5f9cc074fea1cf1e82abfe9e3753f7cd2939087935549a56ec54f7a14"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-linux-amd64"
      binary "memory-bank-cli-linux-amd64", target: "memory-bank-cli"
    end
    on_arm do
      sha256 "db82e05158f232c0b339799fe2791a8a3ddcba2ddfbd9f72cedc5cc0ec607a11"
      url "https://github.com/dapi/memory-bank-cli/releases/download/v#{version}/memory-bank-cli-linux-arm64"
      binary "memory-bank-cli-linux-arm64", target: "memory-bank-cli"
    end
  end

  name "memory-bank-cli"
  desc "CLI for Memory Bank documentation tooling"
  homepage "https://github.com/dapi/memory-bank-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
