# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortSelector < Formula
  desc "Port allocator for parallel local dev environments"
  homepage "https://github.com/dapi/port-selector"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dapi/port-selector/releases/download/v0.10.0/port-selector-darwin-amd64"
      sha256 "6f3b0df452d67c95a77b63833616bb99871cb1531eb7b2cc8fe812ffebebd1be"

      def install
        binary_name = if OS.mac?
          Hardware::CPU.arm? ? "port-selector-darwin-arm64" : "port-selector-darwin-amd64"
        else
          Hardware::CPU.arm? ? "port-selector-linux-arm64" : "port-selector-linux-amd64"
        end
        bin.install binary_name => "port-selector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dapi/port-selector/releases/download/v0.10.0/port-selector-darwin-arm64"
      sha256 "719d230e8232478d0b813384003d0c508540bb54c7d1f3dd91ef886016bc463c"

      def install
        binary_name = if OS.mac?
          Hardware::CPU.arm? ? "port-selector-darwin-arm64" : "port-selector-darwin-amd64"
        else
          Hardware::CPU.arm? ? "port-selector-linux-arm64" : "port-selector-linux-amd64"
        end
        bin.install binary_name => "port-selector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dapi/port-selector/releases/download/v0.10.0/port-selector-linux-amd64"
      sha256 "cd3096db4e81f2598784dc0312b40e9af77d85c1b2ce31dc5a07a205a7fab305"
      def install
        binary_name = if OS.mac?
          Hardware::CPU.arm? ? "port-selector-darwin-arm64" : "port-selector-darwin-amd64"
        else
          Hardware::CPU.arm? ? "port-selector-linux-arm64" : "port-selector-linux-amd64"
        end
        bin.install binary_name => "port-selector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dapi/port-selector/releases/download/v0.10.0/port-selector-linux-arm64"
      sha256 "adef91afc154ecece94a055e0bdf6cd420321a08e9c096ef143210786e0c5cf0"
      def install
        binary_name = if OS.mac?
          Hardware::CPU.arm? ? "port-selector-darwin-arm64" : "port-selector-darwin-amd64"
        else
          Hardware::CPU.arm? ? "port-selector-linux-arm64" : "port-selector-linux-amd64"
        end
        bin.install binary_name => "port-selector"
      end
    end
  end

  test do
    system "#{bin}/port-selector", "--help"
  end
end
