# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortSelector < Formula
  desc "Port allocator for parallel local dev environments"
  homepage "https://github.com/dapi/port-selector"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dapi/port-selector/releases/download/v0.9.2/port-selector-darwin-amd64"
      sha256 "045ea56e2e169ffeacf6e5595f037cd28a0e0fbf7fe30d6958d515be5f916c06"

      def install
        bin.install "port-selector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dapi/port-selector/releases/download/v0.9.2/port-selector-darwin-arm64"
      sha256 "4e42471730ddd596935073068e82fde5ea63def43f61f3fd859c3380b368aca8"

      def install
        bin.install "port-selector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dapi/port-selector/releases/download/v0.9.2/port-selector-linux-amd64"
      sha256 "45dff56b8df0db666bb61e90b838d29053087b6655c46bf8ce153fca42a91344"
      def install
        bin.install "port-selector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dapi/port-selector/releases/download/v0.9.2/port-selector-linux-arm64"
      sha256 "781fd42914ced8d720dfd562e3559c1bb4b6179993a64457f67bfabe14a54118"
      def install
        bin.install "port-selector"
      end
    end
  end

  test do
    system "#{bin}/port-selector", "--help"
  end
end
